- name: Raspberry Pi Update
  hosts: all
  gather_facts: false

  tasks:
    - name: Update Cache
      ansible.builtin.apt:
        update_cache: true

    - name: Upgrade all packages to the latest version
      ansible.builtin.apt:
        upgrade: dist
        install_recommends: true

    - name: Remove useless packages from the cache
      ansible.builtin.apt:
        autoclean: true

    - name: Remove dependencies that are no longer required
      ansible.builtin.apt:
        autoremove: true

    - name: Reboot
      ansible.builtin.reboot:
