- name: Plex Raspberry Pi Install
  hosts: plex

  tasks:
    - name: Update Cache
      ansible.builtin.apt:
        update_cache: true

    - name: Upgrade all packages to the latest version
      ansible.builtin.apt:
        upgrade: dist
        install_recommends: true

    - name: Remove useless packages from the cache
      ansible.builtin.apt:
        autoclean: true

    - name: Remove dependencies that are no longer required
      ansible.builtin.apt:
        autoremove: true

    - name: Install required packages
      ansible.builtin.apt:
        name: 
        - apt-transport-https
        - gnupg2
        - exfat-fuse
        - exfatprogs
        state: present
        update_cache: true
        install_recommends: true

    # - name: Add Plex repo
    #   ansible.builtin.deb822_repository:
    #     name: plex
    #     uris: https://repo.plex.tv/deb/
    #     suites: public
    #     components: main
    #     signed_by: https://downloads.plex.tv/plex-keys/PlexSign.v2.key
    #     state: present
    #     enabled: yes

    ## The below 2 tasks need to be reworked for the new v2 key method and repository location.  I believe the above commented 
    ## "Add Plex repo" task should work. But have not test it yet
    ## https://support.plex.tv/articles/235974187-enable-repository-updating-for-supported-linux-server-distributions/
    # - name: Download Plex Key
    #   ansible.builtin.get_url:
    #     url: https://downloads.plex.tv/plex-keys/PlexSign.key
    #     dest: /etc/apt/trusted.gpg.d/plexsign.asc
    #     mode: '0644'

    # - name: Add Plex repo
    #   ansible.builtin.apt_repository:
    #     repo: deb https://downloads.plex.tv/repo/deb public main
    #     state: present
    #     filename: plexmediaserver

    - name: Update Cache
      ansible.builtin.apt:
        update-cache: true

    - name: Install Plex Media Server
      ansible.builtin.apt:
        name: plexmediaserver
        state: present
        update_cache: true
        install_recommends: true

    - name: Create media mount directory
      ansible.builtin.file:
        path: /media/mediaplus
        mode: '0755'
        state: directory

    - name: Mount media drive
      ansible.posix.mount:
        path: /media/mediaplus
        src: LABEL=mediaplus
        fstype: exfat
        opts: defaults
        state: mounted
