- name: Plex Raspberry Pi Update
  hosts: plex
  
  tasks:
  - name: Update Cache
    ansible.builtin.apt:
      update_cache: yes

  - name: Upgrade all packages to the latest version
    ansible.builtin.apt:
      upgrade: dist
      install_recommends: yes

  - name: Remove useless packages from the cache
    ansible.builtin.apt:
      autoclean: yes

  - name: Remove dependencies that are no longer required
    ansible.builtin.apt:
      autoremove: yes

  - name: Reboot
    ansible.builtin.reboot: